version: "3.8"
services:
  asp.apigateway:
    build:
      context: .
      dockerfile: ./ApiGateway/Dockerfile
    ports:
      - "4030:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
    networks:
      - void-market-network

  asp.order-svc:
    build:
      context: .
      dockerfile: ./OrderService/Dockerfile
    ports:
      - "4033:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
    networks:
      - void-market-network

  asp.payment-svc:
    build:
      context: .
      dockerfile: ./PaymentService/Dockerfile
    ports:
      - "4032:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
    networks:
      - void-market-network

  asp.users-svc:
    build:
      context: .
      dockerfile: ./UserService/Dockerfile
    ports:
      - "4031:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
    networks:
      - void-market-network

networks:
  void-market-network:
    name: void-market-network
    driver: bridge
